# Generated by Django 4.1.6 on 2023-04-11 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medidor',
            fields=[
                ('Llave_Ident', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=20)),
                ('Consumo_max', models.FloatField(default=0.0)),
                ('Consumo_min', models.FloatField(default=0.0)),
                ('Consumo_total', models.FloatField(default=0.0)),
                ('Consumo_prom', models.FloatField(default=0.0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['Nombre'],
            },
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Consumo', models.FloatField(default=0.0)),
                ('Fecha_hora', models.DateTimeField(auto_now=True)),
                ('Medidor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Mediciones', to='drfapi.medidor')),
            ],
        ),
    ]
